name: Test react app
on: push
jobs:
  runs-on: macos
  steps:
    - name: Get repository code
      uses: actions/checkout@v6
    - name: install dependencies
      run: npm ci
    - name: Test application
      run: npm run test
